const char* page_html = "<!DOCTYPE html>\n"
"<html lang=\"en\" >\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <title>Energy indicator settings</title>\n"
"  <style>\n"
"    body {\n"
"  background: #ABCDEF;\n"
"  font-family: Assistant, sans-serif;\n"
"  display: flex;\n"
"  min-height: 90vh;\n"
"}\n"
".login {\n"
"  color: white;\n"
"  background: #136a8a;\n"
"  background: -webkit-linear-gradient(to right, #267871, #136a8a);\n"
"  background: linear-gradient(to right, #267871, #136a8a);\n"
"  margin: auto;\n"
"  box-shadow: \n"
"    0px 2px 10px rgba(0,0,0,0.2), \n"
"    0px 10px 20px rgba(0,0,0,0.3), \n"
"    0px 30px 60px 1px rgba(0,0,0,0.5);\n"
"  border-radius: 8px;\n"
"  padding: 50px;\n"
"}\n"
".login .head {\n"
"  display: flex;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"}\n"
".login .head .company {\n"
"  font-size: 2.2em;\n"
"}\n"
".login .msg {\n"
"  text-align: center;\n"
"}\n"
".login .form input[type=text].text {\n"
"  border: none;\n"
"  background: none;\n"
"  box-shadow: 0px 2px 0px 0px white;\n"
"  width: 100%;\n"
"  color: white;\n"
"  font-size: 1em;\n"
"  outline: none;\n"
"}\n"
".login .form .text::placeholder {\n"
"  color: #D3D3D3;\n"
"}\n"
".login .form input[type=password].password {\n"
"  border: none;\n"
"  background: none;\n"
"  box-shadow: 0px 2px 0px 0px white;\n"
"  width: 100%;\n"
"  color: white;\n"
"  font-size: 1em;\n"
"  outline: none;\n"
"  margin-bottom: 20px;\n"
"  margin-top: 20px;\n"
"}\n"
".login .form .password::placeholder {\n"
"  color: #D3D3D3;\n"
"}\n"
".login .form .btn-login {\n"
"  background: none;\n"
"  text-decoration: none;\n"
"  color: white;\n"
"  box-shadow: 0px 0px 0px 2px white;\n"
"  border-radius: 3px;\n"
"  padding: 5px 2em;\n"
"  transition: 0.5s;\n"
"}\n"
".login .form .btn-login:hover {\n"
"  background: white;\n"
"  color: dimgray;\n"
"  transition: 0.5s;\n"
"}\n"
".login .forgot {\n"
"  text-decoration: none;\n"
"  color: white;\n"
"  float: right;\n"
"}\n"
"footer {\n"
"  position: absolute;\n"
"  color: #136a8a;\n"
"  bottom: 10px;\n"
"  padding-left: 20px;\n"
"}\n"
"footer p {\n"
"  display: inline;\n"
"}\n"
"footer a {\n"
"  color: green;\n"
"  text-decoration: none;\n"
"}\n"
"footer a:hover {\n"
"  text-decoration: underline;\n"
"}\n"
"footer .heart {\n"
"  color: #B22222;\n"
"  font-size: 1.5em\n"
"}\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"<!-- partial:index.partial.html -->\n"
"<section class='login' id='login'>\n"
"  <div class='head'>\n"
"  <h1 class='company'>Energy indicator</h1>\n"
"  </div>\n"
"  <div class='form'>\n"
"  <form id=\"setting-form\">\n"
"    <input type=\"text\" placeholder='SSID' class='text' id='ssid' required><br>\n"
"    <input type=\"password\" placeholder='Password' id=\"pass\" class='password'><br>\n"
"    <input type=\"text\" placeholder='API Key' id=\"api\" class='text'><br>\n"
"    <br>\n"
"    <a class='btn-login' id='do-login'>Save</a>\n"
"  </form>\n"
"  </div>\n"
"</section>\n"
"</body>\n"
"  <script> \n"
"    document.getElementById(\"do-login\").onclick = function() {\n"
"      document.getElementById(\"setting-form\").submit();\n"
"      console.log(httpGet());\n"
"    }\n"
"    function httpGet()\n"
"    {\n"
"      var xmlHttp = new XMLHttpRequest();\n"
"      xmlHttp.open(\"POST\", \"http://192.168.1.1\", false); // false for synchronous request\n"
"      \n"
"      xmlHttp.setRequestHeader(\"SSID\", document.getElementById(\"ssid\").value)\n"
"      xmlHttp.setRequestHeader(\"PASS\", document.getElementById(\"pass\").value)\n"
"      xmlHttp.setRequestHeader(\"API\", document.getElementById(\"api\").value)\n"
"    \n"
"      xmlHttp.send( null );\n"
"      return xmlHttp.responseText;\n"
"    }\n"
"  </script>\n"
"</html>\n"
"";